---
    region: us-east-1
    keypair: aws
    image: ami-0f5c5066b40f2414e
    instances:
      - instance_type: t2.micro
        instance_tags:
          project: devops
          name: appServer
        instance_ids:
          - "app-server"
        security_group: app-server
        count: 1
      - instance_type: t2.micro
        instance_tags:
          project: devops
          name: loadBalancer
        instance_ids:
          - "load-balancer"
        security_group: load-balancer
        count: 1
      - instance_type: t2.micro
        instance_tags:
          project: "devops"
          name: "database"
        instance_ids:
          - "database"
        security_group: database
        count: 1
